version: 2.1

orbs: 
  heroku: circleci/heroku@1.2.6
  docker: circleci/docker@2.0.1

workflows:
  deploy:
    jobs:
      - build_and_test
      - build_push_docker_image:
          requires:
            - build_and_test
      - deploy_heroku:
      # - heroku/deploy_via_git:
          requires:
            - build_and_test
            - build_push_docker_image
          filters:
            branches:
              only: master
              
jobs:
  build_and_test:
    docker:
      - image: cimg/python:3.10.1
    steps:
      - checkout
      - run:
          name: Install Django and dependencies
          command: |
           pip install -r requirements.txt
      - run:
          name: Run tests and linting
          command: |
            pytest
            flake8

  build_push_docker_image:
    docker:
      - image: cimg/python:3.10.1
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: $DOCKER_LOGIN/oc-lettings
          extra_build_args: "-t $DOCKER_LOGIN/oc-lettings"
          tag: 0.1.<< pipeline.number >>
      - docker/push:
          image: $DOCKER_LOGIN/oc-lettings
          tag: "latest"
      - docker/push:
          image: $DOCKER_LOGIN/oc-lettings
          tag: 0.1.<< pipeline.number >>
         
  deploy_heroku:
    docker:
      - image : $DOCKER_LOGIN/oc-lettings:latest
        #auth:
        #  username: $DOCKER_LOGIN
         # password: $DOCKERHUB_PASSWORD  
    steps:
      - setup_remote_docker
      - docker/check
      - heroku/push-docker-image
          

          #_herokupost-deploy:
           # steps:
            #  - run : python manage.py makemigrations && python manage.py migrate

        
      


    



    

